#index:
#    path: /
#    controller: App\Controller\DefaultController::index
index:
    path: /
    controller: App\Controller\XmlTestController::index

load_dumps:
    path: /dumps
    controller: App\Controller\XmlTestController::loadDumps
    methods: [POST]